up-win:
	docker compose -f docker-compose.yml -f docker-compose.override.windows.yml up

up-linux:
	docker compose -f docker-compose.yml -f docker-compose.override.linux.yml up

down-win:
	docker compose -f docker-compose.yml -f docker-compose.override.windows.yml down

down-linux:
	docker compose -f docker-compose.yml -f docker-compose.override.linux.yml down
